### PR TITLE
fix: Add Ably-specific usage example

### PR DESCRIPTION
**Pull request by Peter-Maguire**
## Description

The usage example given was not Ably-specific. This PR updates the usage example to show how this version of Vcdiff would be used with Ably.

Also, a slight renaming of the `const` variable name to match the usage example, and make it clear when specifying the plugin what is the plugin keyname and value name:

```
 plugins: {
        vcdiff: vcdiffPlugin
}
```

The idea is that [this page](https://www.npmjs.com/package/@ably/vcdiff-decoder) would be updated.

### CODE REVIEW

**Comment by owenpearson** [comment]
This addition actually duplicates some of the ably-js README (see [this section](https://github.com/ably/ably-js/#subscribing-to-a-channel-with-deltas) and [this section](https://github.com/ably/ably-js/#subscribing-to-a-channel-with-deltas)), so I'm not sure how best to proceed. It seems like we have three options:
1. Merge this and maintain both READMEs as two unique sources of truth
2. Don't merge this and instead add something to the README which says "For example usage [see the ably-js docs](https://github.com/ably/ably-js/#subscribing-to-a-channel-with-deltas)"
3. Merge this and change the ably-js README to say "For example usage [see the @ably/vcdiff-decoder docs](https://github.com/ably-forks/vcdiff-decoder#usage)"

I personally vote for option 3 since the delta stuff in the ably-js README is just noise which the vast majority of readers won't be interested in. @tbedford @Peter-Maguire WDYT?

**Comment by tbedford** [comment]
I forgot to add it to the PR description, but my intention was to fix [this page](https://www.npmjs.com/package/@ably/vcdiff-decoder). So it seems if I understand it correctly, option 3 would work for me!

**Comment by Peter-Maguire** [comment]
@owenpearson I think option 3 makes the most sense as it would keep the docs closer to the code they relate to

**Comment by tbedford** [comment]
Sorry, there's another fix I need to make. Will push up shortly.

**Review by owenpearson — APPROVED** [review]
LGTM. @Peter-Maguire Are you happy to make that change to the ably-js README?

**Comment by tbedford** [comment]
@owenpearson - is this OK to merge now?

**Comment by owenpearson** [comment]
@tbedford yep, all good. I'll do it now.

**Pull request merged**
